/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/Eyes_Keem.gltf -T 
Files: ./public/Eyes_Keem.gltf [110.65KB] > Eyes_Keem-transformed.glb [9.03KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Eyes_Keem-Small.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={10000000000} near={0.01} fov={31.417} position={[0, 0, 600]} />
      <mesh geometry={nodes.Boole.geometry} material={nodes.Boole.material} position={[-24.442, 4.754, 38.842]} />
    </group>
  )
}

useGLTF.preload('/Eyes_Keem-Small.glb')
